print('Hello World')
print("C:\\number")
zid="My Name is Zidane"
print(zid[0:6])
print(len(zid))
print(zid[0::3])
print(zid[0:17])
print(zid[-4:-1])
print(zid[::-1])
print(zid[::-2])
print(zid.isalnum())
print("MyNameIsZidane".isalnum())
print(zid.endswith("Zidane"))
print(zid.count("M"))
print(zid.count("e"))
print("my name is ZIdane".capitalize())
print(zid.find("Name"))
print("my name my zidane".find("my"))
print(zid.upper())
print(zid.lower())
print(zid.replace("is","are"))
mylist=['py','learn']
for i in mylist:
    i.upper()
    print(i)
print(mylist)